name: Build & Push Docker image to Harbor

on:
  workflow_run:
    workflows: ["Qodana"]
    types: [completed]

env:
  IMAGE_NAME: kube-yaml-service
  REGISTRY: ${{ secrets.HARBOR_REGISTRY }}   # e.g. harbor.example.com (NO https://)
  PROJECT:  ${{ secrets.HARBOR_PROJECT }}    # e.g. platform
  DOCKER_BUILDKIT: 1

jobs:
  build-and-push:
    if: >
      ${{
        github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.event == 'push' &&
        github.event.workflow_run.head_branch == 'main'
      }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout (same commit Qodana scanned)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      # --- Preflight guards (fail early if anything is off) ---
      - name: Validate required secrets/env
        run: |
          test -n "${{ env.REGISTRY }}" || (echo "Missing REGISTRY"; exit 1)
          test -n "${{ env.PROJECT }}"  || (echo "Missing PROJECT"; exit 1)
          test -n "${{ secrets.HARBOR_USERNAME }}" || (echo "Missing HARBOR_USERNAME"; exit 1)
          test -n "${{ secrets.HARBOR_PASSWORD }}" || (echo "Missing HARBOR_PASSWORD"; exit 1)
          case "${{ env.REGISTRY }}" in
            http*|*/|*/*) echo "REGISTRY must be bare host only (e.g. harbor.example.com)"; exit 1;;
          esac

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Build JAR
        run: ./gradlew --no-daemon clean build -x test

      - name: Docker meta (tags/labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.PROJECT }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Verify login (whoami)
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY }}/library/hello-world >/dev/null 2>&1 || true
          echo "Logged into ${{ env.REGISTRY }} as: ${{ secrets.HARBOR_USERNAME }}"

      - name: Build & Push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
